AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run static web site with Apache web server
Resources:
  DurmusCFInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: o
      SecurityGroups:
        - HTTPandSSH
      Tags:
        - Key: Name
          Value: Web server of Kittens Carousel
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 /var/www/html
          cd /var/www/html
          wget https://raw.githubusercontent.com/durmusturk/101-kittens-carousel-static-website-ec2/master/index.html
          wget https://raw.githubusercontent.com/durmusturk/101-kittens-carousel-static-website-ec2/master/cat0.jpg
          wget https://raw.githubusercontent.com/durmusturk/101-kittens-carousel-static-website-ec2/master/cat1.jpg
          wget https://raw.githubusercontent.com/durmusturk/101-kittens-carousel-static-website-ec2/master/cat2.jpg